version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
