package chat

import (
	"fmt"
	"regexp"
	"strings"
)

var (
	// Matches complete thinking blocks:
	// <think>...</think>, <thinking>...</thinking>, <thought>...</thought>
	// Also matches backslash close variants like <think>...<\think> or <thinking>...<\thinking>.
	thinkBlockRegex = regexp.MustCompile(`(?is)<\s*(think|thinking|thought)\b[^>]*>.*?<\s*[/\\]\s*(think|thinking|thought)\s*>`)

	// Matches any opening thinking tag (used to detect unclosed thinking blocks).
	thinkOpenTagRegex = regexp.MustCompile(`(?i)<\s*(think|thinking|thought)\b[^>]*>`)

	// Matches any stray thinking tag (opening, closing with / or \, or backslash tags like <\thinking>).
	strayThinkTagRegex = regexp.MustCompile(`(?i)<\s*[/\\]?\s*(think|thinking|thought)[\s/\\]*>`)

	// Matches code tags like <code>, </code>, <code\>, </code\>, <\code>, <code >.
	codeTagRegex = regexp.MustCompile(`(?i)<\s*[/\\]?\s*code[\s/\\]*>`)

	// Matches markdown code fences: ``` or ~~~
	codeFenceRegex = regexp.MustCompile("(?m)^\\s*(```|~~~)")

	// Matches cut-off tag markers at the end of the text.
	trailingCutOffSlashRegex = regexp.MustCompile(`<\s*[/\\]\s*$`)
	trailingCutOffTagRegex   = regexp.MustCompile(`(?i)<\s*[/\\]?\s*(think|thinking|thought|code)\b[^>]*$`)

	// Speaker role prefixes at the start of string or lines, e.g. "Assistant:", "[Assistant]:", "User:", "System:"
	speakerPrefixRegex = regexp.MustCompile(`(?i)^\s*\[?(assistant|system|user|human|ai)\]?\s*:`)
)

// Known system prompt phrases or delimiters that should never leak into a generated reply.
var leakedPromptPhrases = []string{
	"contextual & temporal guidelines",
	"## contextual",
	"background memory",
	"## background",
	"stay fully in character",
	"never break the persona",
	"reply like a real person texting",
	"never use line breaks",
	"reply to what was just said",
	"go deeper when it feels right",
	"identify if this image is a snap",
	"[received snap",
	"[received video",
	"[voice note:",
	"[spoken in video:",
	"<|im_start|>",
	"<|im_end|>",
	"<|startoftext|>",
	"<|endoftext|>",
	"<|user|>",
	"<|assistant|>",
	"<|system|>",
	"[inst]",
	"[/inst]",
	"<bos>",
	"<eos>",
}

// SanitizeAndValidateReply cleanses and validates the assistant reply generated by the LLM.
// It strips valid complete thinking blocks (<think>...</think>), strips enclosing quotes,
// and rejects partial, incomplete, or corrupted responses with an error.
func SanitizeAndValidateReply(raw string, senderName string) (string, error) {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return "", fmt.Errorf("reply is empty")
	}

	// 1. Check for trailing cut-off tags (e.g. model cut off while emitting a tag like "<\" or "<think")
	if trailingCutOffSlashRegex.MatchString(trimmed) || trailingCutOffTagRegex.MatchString(trimmed) {
		return "", fmt.Errorf("incomplete response: cut-off tag detected at end of reply")
	}

	// 2. Strip complete thinking blocks if present
	cleaned := thinkBlockRegex.ReplaceAllString(trimmed, "")

	// 3. Detect unclosed thinking tag in the original or cleaned text
	if thinkOpenTagRegex.MatchString(cleaned) {
		return "", fmt.Errorf("incomplete response: unclosed thinking tag detected")
	}

	// 4. Detect any stray or corrupted thinking tags (e.g. <\thinking>, </thinking>, <think>)
	if match := strayThinkTagRegex.FindString(cleaned); match != "" {
		return "", fmt.Errorf("invalid response: contains stray thinking tag: %q", match)
	}

	// 5. Detect code tags (e.g. <code\>, <code>, </code>)
	if match := codeTagRegex.FindString(cleaned); match != "" {
		return "", fmt.Errorf("invalid response: contains code tag: %q", match)
	}

	// 6. Detect markdown code fences
	if codeFenceRegex.MatchString(cleaned) {
		return "", fmt.Errorf("invalid response: contains markdown code block")
	}

	// 7. Detect prompt leakage & system token leakage
	lower := strings.ToLower(cleaned)
	for _, phrase := range leakedPromptPhrases {
		if strings.Contains(lower, phrase) {
			return "", fmt.Errorf("invalid response: contains prompt/request leakage: %q", phrase)
		}
	}

	// 8. Detect speaker role prefixes (e.g. "[Assistant]: hello" or "User: hi")
	if match := speakerPrefixRegex.FindString(cleaned); match != "" {
		return "", fmt.Errorf("invalid response: contains speaker prefix: %q", strings.TrimSpace(match))
	}

	// 9. Detect sender name prefix repetition (e.g. "[John]: Hello" when sender is John)
	if senderName != "" {
		senderTag := "[" + strings.ToLower(senderName) + "]:"
		if strings.Contains(lower, senderTag) {
			return "", fmt.Errorf("invalid response: contains sender prompt prefix: %q", senderTag)
		}
		senderColon := strings.ToLower(senderName) + ":"
		if strings.HasPrefix(lower, senderColon) {
			return "", fmt.Errorf("invalid response: contains sender prompt prefix: %q", senderColon)
		}
	}

	// 10. Clean up outer quotes and whitespace
	cleaned = strings.TrimSpace(cleaned)
	if (strings.HasPrefix(cleaned, "\"") && strings.HasSuffix(cleaned, "\"") && len(cleaned) >= 2) ||
		(strings.HasPrefix(cleaned, "'") && strings.HasSuffix(cleaned, "'") && len(cleaned) >= 2) ||
		(strings.HasPrefix(cleaned, "“") && strings.HasSuffix(cleaned, "”") && len(cleaned) >= 2) {
		cleaned = strings.TrimSpace(cleaned[1 : len(cleaned)-1])
	}

	if cleaned == "" {
		return "", fmt.Errorf("reply is empty after stripping thinking blocks")
	}

	return cleaned, nil
}

// SanitizeMediaDescription strips thinking blocks and stray tags from image/audio summaries.
func SanitizeMediaDescription(raw string) (string, error) {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return "", nil
	}
	cleaned := thinkBlockRegex.ReplaceAllString(trimmed, "")
	cleaned = strayThinkTagRegex.ReplaceAllString(cleaned, "")
	cleaned = codeTagRegex.ReplaceAllString(cleaned, "")
	return strings.TrimSpace(cleaned), nil
}
